# Generated by Django 5.0.1 on 2024-02-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='date_created',
            field=models.CharField(default='01.01.2024', max_length=255),
        ),
    ]
