# Generated by Django 5.0.1 on 2024-02-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_good_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image_url',
            field=models.CharField(default='https://img4.labirint.ru/rc/1c536a1679215455457025be87026aa3/363x561q80/books79/787592/cover.jpg?1659961518', max_length=1000),
        ),
    ]
